services:
  - type: web
    name: laravel-app
    env: php
    region: singapore
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      npm install --prefix task-management-frontend
      npm run build --prefix task-management-frontend
      cp -r task-management-frontend/dist/* public/
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-app-name.onrender.com
      - key: NODE_VERSION
        value: 18
